"""tablas de people y planets

Revision ID: 538b59455df1
Revises: a5cffa318ac2
Create Date: 2024-12-16 00:34:09.092805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538b59455df1'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=900), nullable=False),
    sa.Column('eye_color', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=900), nullable=False),
    sa.Column('population', sa.String(length=60), nullable=False),
    sa.Column('climate', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
